### ISSUE TITLE
Encog DotNet 3.3 Multithread Error

### ISSUE THREAD

**Issue by XeonMan** [encog/encog-dotnet-core#89]
Been using Encog CS 3.1, 3.2 and 3.3 on with VS.NET 2015 on two servers, each with dual X5400 series 8 core / 8 thread Xeons without a problem.

I recently tried the exact same code, but compiled (exe) and on the VS IDE on a dual X7500 series 16 core / 32 thread Xeon server and I get this error:

<Exception><ExceptionType>System.OverflowException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Arithmetic operation resulted in an overflow.</Message><StackTrace>   at Encog.Util.Concurrency.DetermineWorkload..ctor(Int32 threads, Int32 workloadSize)
   at Encog.Neural.Networks.Training.Propagation.Propagation.Init()
   at Encog.Neural.Networks.Training.Propagation.Propagation.CalculateGradients()
   at Encog.Neural.Networks.Training.Propagation.Propagation.ProcessPureBatch()
   at Encog.Neural.Networks.Training.Propagation.Propagation.Iteration()
   at EncogConsole.modEncog.ElmanTypeA(Boolean boolErrorVerbose, Boolean boolTestOutput) in C:\Users\Administrator\Documents\Visual Studio 2015\Projects\NormalizedConsole_v4B\EncogConsole\modEncog.vb:line 126
   at EncogConsole.modEncog.Main() in C:\Users\Administrator\Documents\Visual Studio 2015\Projects\NormalizedConsole_v4B\EncogConsole\modEncog.vb:line 35
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</StackTrace><ExceptionString>System.OverflowException: Arithmetic operation resulted in an overflow.
   at Encog.Util.Concurrency.DetermineWorkload..ctor(Int32 threads, Int32 workloadSize)
   at Encog.Neural.Networks.Training.Propagation.Propagation.Init()
   at Encog.Neural.Networks.Training.Propagation.Propagation.CalculateGradients()
   at Encog.Neural.Networks.Training.Propagation.Propagation.ProcessPureBatch()
   at Encog.Neural.Networks.Training.Propagation.Propagation.Iteration()
   at EncogConsole.modEncog.ElmanTypeA(Boolean boolErrorVerbose, Boolean boolTestOutput) in C:\Users\Administrator\Documents\Visual Studio 2015\Projects\NormalizedConsole_v4B\EncogConsole\modEncog.vb:line 126
   at EncogConsole.modEncog.Main() in C:\Users\Administrator\Documents\Visual Studio 2015\Projects\NormalizedConsole_v4B\EncogConsole\modEncog.vb:line 35
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</ExceptionString></Exception></TraceRecord>	0.31s		

The thing here is that the code is the exact same, with the exact same datasets, etc. Tried different code that's running fine on the first two servers and still the same problem.

Code is done with VB, but as said before, works just fine, except on this higher thread count server.

What gives?

**Comment by XeonMan** [comment]
Suggest using:

var num = (int)Environment.ProcessorCount;

instead of:

var num = (int) (Math.Log(((int) Process.GetCurrentProcess().ProcessorAffinity + 1), 2));

to get the processor (thread) count in:

Encog.Util.Concurrency.DetermineWorkload > public DetermineWorkload(int threads, int workloadSize)

as var num = (int) (Math.Log(((int) Process.GetCurrentProcess().ProcessorAffinity + 1), 2)); returns 4294967295 for a 32 thread systems whereas Environment.ProcessorCount correctly returns 32.
